### ISSUE TITLE
hyper_sh 1.0.3 does not create containers on python3

### ISSUE THREAD

**Issue by pmatos** [tardyp/hyper_sh#12]
I was chasing the root cause of buildbot/buildbot#3723 and found that the following snippet doesn't work with Python3:

```python
from hyper_sh import Client

c = Client({'clouds': {
    'https://eu-central-1.hyper.sh:443': {
        'accesskey': 'sdfasdfasdf',
        'secretkey': 'sdfasdfasdfasdf'
        }
    }})

c.create_container('ubuntu:latest', name='foo')
```

With python 3.6.2 I get:
```
Traceback (most recent call last):
  File "/home/pmatos/.pyenv/versions/test-hyper-venv/lib/python3.6/site-packages/docker/client.py", line 170, in _raise_for_status
    response.raise_for_status()
  File "/home/pmatos/.pyenv/versions/test-hyper-venv/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://eu-central-1.hyper.sh:443/v1.23/containers/create?name=foo

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hyper.py", line 10, in <module>
    c.create_container('ubuntu:latest', name='foo')
  File "/home/pmatos/.pyenv/versions/test-hyper-venv/lib/python3.6/site-packages/docker/api/container.py", line 135, in create_container
    return self.create_container_from_config(config, name)
  File "/home/pmatos/.pyenv/versions/test-hyper-venv/lib/python3.6/site-packages/docker/api/container.py", line 146, in create_container_from_config
    return self._result(res, True)
  File "/home/pmatos/.pyenv/versions/test-hyper-venv/lib/python3.6/site-packages/docker/client.py", line 178, in _result
    self._raise_for_status(response)
  File "/home/pmatos/.pyenv/versions/test-hyper-venv/lib/python3.6/site-packages/docker/client.py", line 173, in _raise_for_status
    raise errors.NotFound(e, response, explanation=explanation)
docker.errors.NotFound: 404 Client Error: Not Found ("b'No such image: ubuntu:latest'")
```

And python 2.7.13:
```
Traceback (most recent call last):
  File "hyper.py", line 10, in <module>
    c.create_container('ubuntu:latest', name='foo')
  File "/home/pmatos/.pyenv/versions/hyper_venv_2.7/lib/python2.7/site-packages/docker/api/container.py", line 135, in create_container
    return self.create_container_from_config(config, name)
  File "/home/pmatos/.pyenv/versions/hyper_venv_2.7/lib/python2.7/site-packages/docker/api/container.py", line 146, in create_container_from_config
    return self._result(res, True)
  File "/home/pmatos/.pyenv/versions/hyper_venv_2.7/lib/python2.7/site-packages/docker/client.py", line 178, in _result
    self._raise_for_status(response)
  File "/home/pmatos/.pyenv/versions/hyper_venv_2.7/lib/python2.7/site-packages/docker/client.py", line 173, in _raise_for_status
    raise errors.NotFound(e, response, explanation=explanation)
docker.errors.NotFound: 404 Client Error: Not Found ("No such image: ubuntu:latest")
```

I don't know much about `hyper` yet but my guess is that I need to have the image loaded in hyper before creating the container. I don't and so it fails with python2.7. However, I can't see a reason for it to fail with python 3.6. I think this is python3.6 related.

**Comment by berryp** [comment]
This is not a `hyper_sh` issue. I've found you often need to `hyper pull <image[:tag]>` to get the image into your Hyper account's images list. Seems counter-intuitive and I don't know if that's always the case, but I've experienced this recently a few times. I tested using using the Hyper CLI with images I've not used on my account before, such as `busybox`. I'm not sure why this happens.
